In [1]:
import argos
from argos import ArgosDataset
import pandas as pd
import numpy as np

## Importando dados

In [2]:
metadata = pd.read_csv("../data/processed/metadata_filtrada.csv")
metadata.head()

,Species,Source,Date,Location,sample,BioSample,Estado,Região,source_type,WHO_Priority
0,Leptospira interrogans,Homo sapiens,NaN,Salvador,GCA_000216055.2,SAMN00254327,BA,Nordeste,Other,Other
1,Escherichia coli,NaN,1990.0,Brazil,GCA_000316425.1,SAMN01041333,NaN,NaN,Unknown,Critical
2,Vibrio cholerae,patient with cholera-like diarrhea,1991.0,NaN,GCA_000223095.2,SAMN02470783,NaN,NaN,Gastrointestinal,Other
3,Acinetobacter bereziniae,Rectal Swab,2019.0,Brazil,GCA_036761135.1,SAMN39408214,NaN,NaN,Gastrointestinal,Other
4,Acinetobacter bereziniae,Endotracheal aspirate,2014.0,"Londrina, PR",GCA_003670255.1,SAMN09907131,PR,Sul,Respiratory,Other

In [3]:
ids_finais = metadata["sample"].tolist()
dataset = ArgosDataset.from_parquet("../data/argos_project/parquet_data", samples=ids_finais)
dataset.resistome.head()

,ORF_ID,Cut_Off,Pass_Bitscore,Best_Hit_Bitscore,Best_Identities,drug_class,mechanism,amr_gene_family,Predicted_Protein,CARD_Protein_Sequence,...,gene,aro_accession,model_type,gene_clean,seq_name,start,end,strand,length_nt,contig_type
0,ABSC01000258.1_1 # 45 # 395 # 1 # ID=83_1;part...,Strict,100,115.931,42.98,{phosphonic acid antibiotic},{antibiotic inactivation},{fosfomycin thiol transferase},MLNTLFDAKEIYDSQQKKFSLYPEKFFLVKDLWIAVMQNSSNKLPK...,MKGISHITFIVRDLNRMAALLCEGLGAREVYDSSNQNFSLSREKFF...,...,FosI,ARO:3007370,protein homolog model,FosI,ABSC01000258.1,45,395,1,351,chromosome
1,ABSC01000180.1_7 # 6357 # 7019 # -1 # ID=161_7...,Strict,50,220.705,57.14,{glycopeptide antibiotic},{antibiotic target alteration},"{vanY, glycopeptide resistance gene cluster}",MKRSYKTVAVILLIVLLASIGLFFRKTPQKIQVCGEERDSWNLLLV...,MEKSNYHSNVNHHKRHMKQSGEKRAFLWAFIISFTVCTLFLGWRLV...,...,vanY gene in vanB cluster,ARO:3002956,protein homolog model,vanY_in_vanB_cl,ABSC01000180.1,6357,7019,-1,663,chromosome
2,ABSC01000175.1_1 # 81 # 1520 # -1 # ID=166_1;p...,Strict,900,966.066,99.79,{aminoglycoside antibiotic},{antibiotic inactivation},{aminoglycoside bifunctional resistance protein},MNIVENEICIRTLIDDDFPLMLKWLTDERVLEFYDGRDKKYTLESL...,MNIVENEICIRTLIDDDFPLMLKWLTDERVLEFYGGRDKKYTLESL...,...,AAC(6')-Ie-APH(2'')-Ia bifunctional protein,ARO:3002597,protein homolog model,AAC6_Ie_APH2_Ia,ABSC01000175.1,81,1520,-1,1440,chromosome
3,ABSC01000090.1_4 # 3146 # 4876 # 1 # ID=251_4;...,Strict,960,989.949,82.81,"{fluoroquinolone antibiotic, macrolide antibio...",{antibiotic efflux},{ATP-binding cassette (ABC) antibiotic efflux ...,MKLMWHYTMRYKKFLFFNFICVFGFILIELGLPTILARMIDVGIRN...,MKLMWRYTMRYKKLLFADFICVFGFILIELGLPTILARMIDKGIIP...,...,efrA,ARO:3003948,protein homolog model,efrA,ABSC01000090.1,3146,4876,1,1731,chromosome
4,ABSC01000050.1_4 # 2667 # 3404 # 1 # ID=291_4;...,Strict,400,489.574,97.96,"{lincosamide antibiotic, macrolide antibiotic,...",{antibiotic target alteration},{Erm 23S ribosomal RNA methyltransferase},MNKNIKYSQNFLTSEKVLNQIIKQLNLKETDTVYEIGTGKGHLTTK...,MNKNIKYSQNFLTSEKVLNQIIKQLNLKETDTVYEIGTGKGHLTTK...,...,ErmB,ARO:3000375,protein homolog model,ErmB,ABSC01000050.1,2667,3404,1,738,plasmid

In [4]:
vfdb = pd.read_csv('../data/raw/vfdb_all_hits.csv')

vfdb.head()

,#FILE,SEQUENCE,START,END,STRAND,GENE,COVERAGE,COVERAGE_MAP,GAPS,%COVERAGE,%IDENTITY,DATABASE,ACCESSION,PRODUCT,RESISTANCE,sample,categoria
0,../genomes//GCA_052400065.1_ASM5240006v1_genom...,JBQTZX010000001.1,6381,7271,-,inlC,1-891/891,===============,0/0,100.0,97.19,vfdb,NP_465311,(inlC) internalin C [InlC (VF0438) - Immune mo...,NaN,GCA_052400065.1_ASM5240006v1_genomic,Immune modulation
1,../genomes//GCA_052400065.1_ASM5240006v1_genom...,JBQTZX010000001.1,50025,51737,+,fbpA,1-1713/1713,===============,0/0,100.0,91.71,vfdb,NP_465354,(fbpA) fibronectin-binding protein [FbpA (VF03...,NaN,GCA_052400065.1_ASM5240006v1_genomic,Adherence
2,../genomes//GCA_052400065.1_ASM5240006v1_genom...,JBQTZX010000001.1,66308,66772,-,lspA,1-465/465,===============,0/0,100.0,97.42,vfdb,NP_465369,(lspA) signal peptidase II [Lsp (VF0351) - Pos...,NaN,GCA_052400065.1_ASM5240006v1_genomic,Post-translational modification
3,../genomes//GCA_052400065.1_ASM5240006v1_genom...,JBQTZX010000001.1,69697,70629,-,lpeA,1-933/933,===============,0/0,100.0,96.68,vfdb,NP_465372,(lpeA) lipoprotein promoting cell invasion [Lp...,NaN,GCA_052400065.1_ASM5240006v1_genomic,Invasion
4,../genomes//GCA_052400065.1_ASM5240006v1_genom...,JBQTZX010000001.1,301597,302574,-,bsh,1-978/978,===============,0/0,100.0,97.75,vfdb,NP_465591,(bsh) bile salt hydrolase [BSH (VF0350) - Stre...,NaN,GCA_052400065.1_ASM5240006v1_genomic,Stress survival

## Fazendo as `features`

### Ajustando metadata

In [5]:
# Reindexando o `metadata` pra eliminar erro futuro
metadata = metadata.set_index("sample")
metadata.head(n=3)

,Species,Source,Date,Location,BioSample,Estado,Região,source_type,WHO_Priority
sample,,,,,,,,,
GCA_000216055.2,Leptospira interrogans,Homo sapiens,NaN,Salvador,SAMN00254327,BA,Nordeste,Other,Other
GCA_000316425.1,Escherichia coli,NaN,1990.0,Brazil,SAMN01041333,NaN,NaN,Unknown,Critical
GCA_000223095.2,Vibrio cholerae,patient with cholera-like diarrhea,1991.0,NaN,SAMN02470783,NaN,NaN,Gastrointestinal,Other

### Matrizes

In [6]:
def matriz_por_contig_type(resistome, contig_type) -> pd.DataFrame:
    hits = resistome[resistome['contig_type'] == contig_type]
    matriz = pd.crosstab(hits['sample_id'], hits['gene_clean']).clip(upper=1)
    return matriz.reindex(metadata.index, fill_value= 0) # pra genomas sem hits == 0

In [7]:
matriz_cromossomal = matriz_por_contig_type(dataset.resistome, "chromosome")
matriz_cromossomal.head(n=3)

gene_clean,AAC(2')-IIa,AAC(2')-Ia,AAC(2')-Ic,AAC(3)-IIc,AAC(3)-IId,AAC(3)-IIe,AAC(3)-IIg,AAC(3)-IVa,AAC(3)-Ia,AAC(3)-VIIa,...,vanX_in_vanP_cl,vanY_in_vanA_cl,vanY_in_vanB_cl,vanY_in_vanD_cl,vanY_in_vanF_cl,vanY_in_vanG_cl,vanY_in_vanM_cl,vanZ_in_vanA_cl,vatD,vatF
sample,,,,,,,,,,,,,,,,,,,,,
GCA_000216055.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
GCA_000316425.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GCA_000223095.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
matriz_plasmidial = matriz_por_contig_type(dataset.resistome, "plasmid")
matriz_plasmidial.head(n=3)

gene_clean,AAC(2')-Ia,AAC(2')-Ic,AAC(3)-IIc,AAC(3)-IId,AAC(3)-IIe,AAC(3)-IIg,AAC(3)-IVa,AAC(3)-Ia,AAC(3)-VIa,AAC(6')-31,...,vanW_in_vanG_cl,vanW_in_vanI_cl,vanXY_in_vanG,vanX_in_vanA_cl,vanY_in_vanA_cl,vanY_in_vanB_cl,vanY_in_vanF_cl,vanY_in_vanM_cl,vanZ_in_vanA_cl,vgaALC
sample,,,,,,,,,,,,,,,,,,,,,
GCA_000216055.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GCA_000316425.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GCA_000223095.2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### n_genes e mdr_score

In [9]:
n_genes_cromossomal = matriz_cromossomal.sum(axis=1).rename("n_genes_cromossomal")
n_genes_plasmidial = matriz_plasmidial.sum(axis=1).rename("n_genes_plasmidial")

n_genes_plasmidial.head()

sample
GCA_000216055.2    0
GCA_000316425.1    1
GCA_000223095.2    0
GCA_036761135.1    6
GCA_003670255.1    7
Name: n_genes_plasmidial, dtype: int64

In [10]:
# Método do argos que agrupa por classe de droga
argos.groupby_genes(matriz_cromossomal, dataset.annotations, by='drug_class_compacted', agg='max').head(n=3)

,Aminoglycoside,Antimycobacterial,Beta-lactam,Biocide/Antiseptic,Fluoroquinolone,Glycopeptide,MLS,Nitroimidazole,Other,Oxazolidinone,...,Pleuromutilin,Rifamycin,Sulfonamide/Diaminopyrimidine,Tetracycline,cycloserine-like antibiotic,moenomycin antibiotic,mupirocin-like antibiotic,salicylic acid antibiotic,thioamide antibiotic,thiosemicarbazone antibiotic
sample,,,,,,,,,,,,,,,,,,,,,
GCA_000216055.2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
GCA_000316425.1,1,0,1,1,1,1,1,1,1,0,...,0,1,1,1,0,0,0,0,0,0
GCA_000223095.2,0,0,1,0,1,1,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [11]:
mdr_score_cromossomal = argos.groupby_genes(
    matriz_cromossomal, dataset.annotations, by="drug_class_compacted", agg="max"
).sum(axis=1).rename("mdr_score_cromossomal")

mdr_score_plasmidial = argos.groupby_genes(
    matriz_plasmidial, dataset.annotations, by="drug_class_compacted", agg="max"
).sum(axis=1).rename("mdr_score_plasmidial")

mdr_score_plasmidial.head()

sample
GCA_000216055.2    0
GCA_000316425.1    6
GCA_000223095.2    0
GCA_036761135.1    5
GCA_003670255.1    5
Name: mdr_score_plasmidial, dtype: int64

### Tipo de contig

In [12]:
contagem_tipo_contig = pd.crosstab(dataset.contigs["sample_id"], dataset.contigs["contig_type"])
contagem_tipo_contig.head()

contig_type      chromosome  plasmid  virus
sample_id
GCA_000172875.1         293       34     13
GCA_000188755.2         116       36     47
GCA_000188815.2          46        5     12
GCA_000188875.2          43       16     14
GCA_000208825.1         139       10      0

In [13]:
percentual_contig = contagem_tipo_contig.div(contagem_tipo_contig.sum(axis=1), axis=0) * 100
percentual_contig = percentual_contig.reindex(metadata.index, fill_value=0)
percentual_contig.head()

contig_type      chromosome    plasmid      virus
sample
GCA_000216055.2   97.350993   1.655629   0.993377
GCA_000316425.1   67.567568   5.675676  26.756757
GCA_000223095.2   93.650794   6.349206   0.000000
GCA_036761135.1   79.807692  18.269231   1.923077
GCA_003670255.1   74.688797  22.406639   2.904564

In [14]:
pct_contigs_cromossomal = percentual_contig.get("chromosome", 0).rename("pct_contigs_cromossomal")
pct_contigs_plasmidial = percentual_contig.get("plasmid", 0).rename("pct_contigs_plasmidial")

pct_contigs_plasmidial.head()

sample
GCA_000216055.2     1.655629
GCA_000316425.1     5.675676
GCA_000223095.2     6.349206
GCA_036761135.1    18.269231
GCA_003670255.1    22.406639
Name: pct_contigs_plasmidial, dtype: float64

### Contigs plasmidiais

In [15]:
contigs_plasmid = dataset.contigs[dataset.contigs["contig_type"] == "plasmid"].copy()
contigs_plasmid.head(n=3)

,seq_name,c_score,p_score,v_score,sample_id,contig_type,length_nt,topology,n_genes,n_hallmarks,...,plasmid_genes,n_plasmid_genes,virus_genes,n_virus_genes,conjugation_genes,n_conjugation_genes,genomad_amr_genes,n_genomad_amr_genes,amr_list,amr
9,ABSC01000331.1,0.0081,0.9805,0.0114,GCA_000172875.1,plasmid,3122.0,No terminal repeats,4.0,0.0,...,"[ABSC01000331.1_1, ABSC01000331.1_2, ABSC01000...",4,[],0,[],0,[],0,[],0
16,ABSC01000324.1,0.1473,0.8130,0.0397,GCA_000172875.1,plasmid,10961.0,No terminal repeats,13.0,0.0,...,"[ABSC01000324.1_1, ABSC01000324.1_10, ABSC0100...",13,[],0,[],0,[],0,[],0
20,ABSC01000320.1,0.0010,0.9962,0.0028,GCA_000172875.1,plasmid,4674.0,No terminal repeats,9.0,1.0,...,"[ABSC01000320.1_1, ABSC01000320.1_2, ABSC01000...",9,[],0,[ABSC01000320.1_7],1,[],0,[],0

In [16]:
contigs_plasmid.value_counts('topology')

topology
No terminal repeats    103367
DTR                      2072
ITR                       795
Name: count, dtype: int64

In [17]:
topology_pct = (
    pd.crosstab(contigs_plasmid["sample_id"], contigs_plasmid["topology"], normalize="index") * 100
).reindex(metadata.index, fill_value=0)

topology_pct.columns = [
    f"pct_plasmid_topology_{c.lower().replace(' ', '_')}" for c in topology_pct.columns
]

# pra cada genoma, dos plasmídeos que ele tem, quanto % é circular fechado (DTR/ITR) ou fragmento linear sem repetição terminal
topology_pct.head()

,pct_plasmid_topology_dtr,pct_plasmid_topology_itr,pct_plasmid_topology_no_terminal_repeats
sample,,,
GCA_000216055.2,0.000000,0.0,100.000000
GCA_000316425.1,4.761905,0.0,95.238095
GCA_000223095.2,0.000000,0.0,100.000000
GCA_036761135.1,0.000000,0.0,100.000000
GCA_003670255.1,1.851852,0.0,98.148148

In [18]:
contigs_plasmid["tem_amr"] = contigs_plasmid["amr"] > 0
contigs_plasmid["tem_conjugacao"] = contigs_plasmid["n_conjugation_genes"] > 0
contigs_plasmid["conjugacao_e_amr"] = contigs_plasmid["tem_amr"] & contigs_plasmid["tem_conjugacao"]

resumo_plasmid_contig = contigs_plasmid.groupby("sample_id").agg(
    n_contigs_plasmidiais=("seq_name", "count"),
    n_contigs_plasmid_amr=("tem_amr", "sum"),
    n_contigs_plasmid_conj_amr=("conjugacao_e_amr", "sum"),
).reindex(metadata.index, fill_value=0)

resumo_plasmid_contig.head()

,n_contigs_plasmidiais,n_contigs_plasmid_amr,n_contigs_plasmid_conj_amr
sample,,,
GCA_000216055.2,5,0,0
GCA_000316425.1,21,1,0
GCA_000223095.2,4,0,0
GCA_036761135.1,38,4,1
GCA_003670255.1,54,5,1

In [19]:
# Transforma em %
pct_plasmidial_amr = (
    100 * resumo_plasmid_contig["n_contigs_plasmid_amr"] / resumo_plasmid_contig["n_contigs_plasmidiais"]
).fillna(0).rename("pct_plasmidial_amr")

pct_plasmidial_conjugacao_amr = (
    100 * resumo_plasmid_contig["n_contigs_plasmid_conj_amr"] / resumo_plasmid_contig["n_contigs_plasmidiais"]
).fillna(0).rename("pct_plasmidial_conjugacao_amr")

pct_plasmidial_conjugacao_amr.head()

sample
GCA_000216055.2    0.000000
GCA_000316425.1    0.000000
GCA_000223095.2    0.000000
GCA_036761135.1    2.631579
GCA_003670255.1    1.851852
Name: pct_plasmidial_conjugacao_amr, dtype: float64

In [20]:
genes_conjugativos_por_amostra = (
    contigs_plasmid[contigs_plasmid["tem_conjugacao"]][["sample_id", "amr_list"]]
    .explode("amr_list").dropna(subset=["amr_list"])
    .groupby("sample_id")["amr_list"].nunique()
)
n_genes_plasmidial_conjugativo = genes_conjugativos_por_amostra.reindex(
    metadata.index, fill_value=0
).rename("n_genes_plasmidial_conjugativo")

# número de genes AMR distintos presentes em contigs plasmidiais que também carregam genes de conjugação especificamente (n_conjugation_genes > 0)
n_genes_plasmidial_conjugativo.head()

sample
GCA_000216055.2    0
GCA_000316425.1    0
GCA_000223095.2    0
GCA_036761135.1    1
GCA_003670255.1    1
Name: n_genes_plasmidial_conjugativo, dtype: int64

### Matriz de genes por drug class (em contigs plasmidiais)

In [21]:
matriz_drugclass_plasmidial = argos.groupby_genes(
    matriz_plasmidial, dataset.annotations, by="drug_class_compacted", agg="sum"
)
matriz_drugclass_plasmidial.columns = [
    f"n_plasmidial_{c.lower().replace('/', '_').replace(' ', '_')}" for c in matriz_drugclass_plasmidial.columns
]

matriz_drugclass_plasmidial.head()

,n_plasmidial_aminoglycoside,n_plasmidial_antimycobacterial,n_plasmidial_beta-lactam,n_plasmidial_biocide_antiseptic,n_plasmidial_fluoroquinolone,n_plasmidial_glycopeptide,n_plasmidial_mls,n_plasmidial_nitroimidazole,n_plasmidial_other,n_plasmidial_oxazolidinone,n_plasmidial_peptide,n_plasmidial_phenicol,n_plasmidial_phosphonic_acid,n_plasmidial_pleuromutilin,n_plasmidial_rifamycin,n_plasmidial_sulfonamide_diaminopyrimidine,n_plasmidial_tetracycline,n_plasmidial_moenomycin_antibiotic,n_plasmidial_mupirocin-like_antibiotic,n_plasmidial_thiosemicarbazone_antibiotic
sample,,,,,,,,,,,,,,,,,,,,
GCA_000216055.2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
GCA_000316425.1,0,0,1,1,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0
GCA_000223095.2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
GCA_036761135.1,0,0,1,1,0,0,2,0,0,0,0,0,0,0,0,1,1,0,0,0
GCA_003670255.1,1,0,3,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0

### Matriz de classes de genes de virulencia (vfdb - matriz preparada anteriormente)

In [22]:
vfdb.head(n=2)

,#FILE,SEQUENCE,START,END,STRAND,GENE,COVERAGE,COVERAGE_MAP,GAPS,%COVERAGE,%IDENTITY,DATABASE,ACCESSION,PRODUCT,RESISTANCE,sample,categoria
0,../genomes//GCA_052400065.1_ASM5240006v1_genom...,JBQTZX010000001.1,6381,7271,-,inlC,1-891/891,===============,0/0,100.0,97.19,vfdb,NP_465311,(inlC) internalin C [InlC (VF0438) - Immune mo...,NaN,GCA_052400065.1_ASM5240006v1_genomic,Immune modulation
1,../genomes//GCA_052400065.1_ASM5240006v1_genom...,JBQTZX010000001.1,50025,51737,+,fbpA,1-1713/1713,===============,0/0,100.0,91.71,vfdb,NP_465354,(fbpA) fibronectin-binding protein [FbpA (VF03...,NaN,GCA_052400065.1_ASM5240006v1_genomic,Adherence

In [23]:
vfdb["sample_id"] = vfdb["sample"].str.extract(r"(GC[AF]_\d+\.\d+)")

print(vfdb["sample_id"].isna().sum())
vfdb.head(n=2)

0

,#FILE,SEQUENCE,START,END,STRAND,GENE,COVERAGE,COVERAGE_MAP,GAPS,%COVERAGE,%IDENTITY,DATABASE,ACCESSION,PRODUCT,RESISTANCE,sample,categoria,sample_id
0,../genomes//GCA_052400065.1_ASM5240006v1_genom...,JBQTZX010000001.1,6381,7271,-,inlC,1-891/891,===============,0/0,100.0,97.19,vfdb,NP_465311,(inlC) internalin C [InlC (VF0438) - Immune mo...,NaN,GCA_052400065.1_ASM5240006v1_genomic,Immune modulation,GCA_052400065.1
1,../genomes//GCA_052400065.1_ASM5240006v1_genom...,JBQTZX010000001.1,50025,51737,+,fbpA,1-1713/1713,===============,0/0,100.0,91.71,vfdb,NP_465354,(fbpA) fibronectin-binding protein [FbpA (VF03...,NaN,GCA_052400065.1_ASM5240006v1_genomic,Adherence,GCA_052400065.1

In [24]:
def matriz_vfdb_por_contig_type(vfdb, contig_type_map, contig_type):
    hits = vfdb[vfdb["SEQUENCE"].map(contig_type_map) == contig_type]
    matriz = pd.crosstab(hits["sample_id"], hits["categoria"])   # <- era hits["sample"]
    matriz = matriz.reindex(metadata.index, fill_value=0)
    matriz.columns = [f"vfdb_{contig_type}_{c.lower().replace('/', '_').replace(' ', '_')}" for c in matriz.columns]
    return matriz

In [25]:
contig_type_map = dataset.contigs.set_index("seq_name")["contig_type"]

vfdb_cromossomal = matriz_vfdb_por_contig_type(vfdb, contig_type_map, "chromosome")
vfdb_plasmidial = matriz_vfdb_por_contig_type(vfdb, contig_type_map, "plasmid")

print(vfdb_plasmidial.sum().sum())
vfdb_plasmidial.loc["GCA_009651075.1"]

87025

vfdb_plasmid_adherence                                        0
vfdb_plasmid_antimicrobial_activity_competitive_advantage     0
vfdb_plasmid_biofilm                                          0
vfdb_plasmid_effector_delivery_system                         4
vfdb_plasmid_exoenzyme                                        0
vfdb_plasmid_exotoxin                                         0
vfdb_plasmid_immune_modulation                                2
vfdb_plasmid_invasion                                         0
vfdb_plasmid_motility                                         0
vfdb_plasmid_nutritional_metabolic_factor                    12
vfdb_plasmid_others                                           0
vfdb_plasmid_regulation                                       1
vfdb_plasmid_stress_survival                                  0
Name: GCA_009651075.1, dtype: int64

In [26]:
virulence_score_cromossomal = vfdb_cromossomal.clip(upper=1).sum(axis=1).rename("virulence_score_cromossomal")
virulence_score_plasmidial = vfdb_plasmidial.clip(upper=1).sum(axis=1).rename("virulence_score_plasmidial")

virulence_score_plasmidial.loc["GCA_009651075.1"]  # tem 1 ser 4

np.int64(4)

### Verificando provirus - bacteriófago que está integrado no genoma

In [27]:
provirus_genes = dataset.genomad_genes[
    dataset.genomad_genes["gene_id"].str.contains(r"\|provirus_\d+_")
].copy()

print(provirus_genes.shape)
provirus_genes.head()

(823212, 24)

,gene_id,start,end,length_nt,strand,gc_content,genetic_code,rbs_motif,marker,evalue,...,taxid,taxname,annotation_conjscan,annotation_amr,annotation_accessions,annotation_description,sample_id,element_type,has_amr,seq_name
2804899,ABSC01000183.1|provirus_1_11483_1,1,183,183,-1,0.464,11,AGGAG/GGAGG,GENOMAD.023403.VV,2.105000e-32,...,1246,Caudoviricetes,None,None,PF05263;TIGR01637,"phage transcriptional regulator, ArpU family",GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483
2804900,ABSC01000183.1|provirus_1_11483_2,259,555,297,-1,0.397,11,AGGAG,GENOMAD.096602.VV,1.238000e-55,...,1246,Caudoviricetes,None,None,PF09953;COG4873,"Uncharacterized protein YkvS, DUF2187 family",GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483
2804901,ABSC01000183.1|provirus_1_11483_3,579,884,306,-1,0.363,11,AGGAG,None,NaN,...,1,None,None,None,None,None,GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483
2804902,ABSC01000183.1|provirus_1_11483_4,900,1097,198,-1,0.303,11,AGGAG,GENOMAD.093693.VV,3.811000e-21,...,1246,Caudoviricetes,None,None,None,None,GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483
2804903,ABSC01000183.1|provirus_1_11483_5,1094,1393,300,-1,0.387,11,GGAG/GAGG,GENOMAD.183400.VP,8.799000e-13,...,2200,Kochikohdavirus,None,None,None,None,GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483

In [28]:
# extrai o contig hospedeiro (antes do "|") de cada gene de provírus
provirus_genes["host_contig"] = provirus_genes["seq_name"].str.split("|").str[0]

provirus_genes.head()

,gene_id,start,end,length_nt,strand,gc_content,genetic_code,rbs_motif,marker,evalue,...,taxname,annotation_conjscan,annotation_amr,annotation_accessions,annotation_description,sample_id,element_type,has_amr,seq_name,host_contig
2804899,ABSC01000183.1|provirus_1_11483_1,1,183,183,-1,0.464,11,AGGAG/GGAGG,GENOMAD.023403.VV,2.105000e-32,...,Caudoviricetes,None,None,PF05263;TIGR01637,"phage transcriptional regulator, ArpU family",GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483,ABSC01000183.1
2804900,ABSC01000183.1|provirus_1_11483_2,259,555,297,-1,0.397,11,AGGAG,GENOMAD.096602.VV,1.238000e-55,...,Caudoviricetes,None,None,PF09953;COG4873,"Uncharacterized protein YkvS, DUF2187 family",GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483,ABSC01000183.1
2804901,ABSC01000183.1|provirus_1_11483_3,579,884,306,-1,0.363,11,AGGAG,None,NaN,...,None,None,None,None,None,GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483,ABSC01000183.1
2804902,ABSC01000183.1|provirus_1_11483_4,900,1097,198,-1,0.303,11,AGGAG,GENOMAD.093693.VV,3.811000e-21,...,Caudoviricetes,None,None,None,None,GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483,ABSC01000183.1
2804903,ABSC01000183.1|provirus_1_11483_5,1094,1393,300,-1,0.387,11,GGAG/GAGG,GENOMAD.183400.VP,8.799000e-13,...,Kochikohdavirus,None,None,None,None,GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483,ABSC01000183.1

In [29]:
host_contig_type = dataset.contigs.set_index("seq_name")["contig_type"]
provirus_genes["host_contig_type"] = provirus_genes["host_contig"].map(host_contig_type)

provirus_genes.head()

,gene_id,start,end,length_nt,strand,gc_content,genetic_code,rbs_motif,marker,evalue,...,annotation_conjscan,annotation_amr,annotation_accessions,annotation_description,sample_id,element_type,has_amr,seq_name,host_contig,host_contig_type
2804899,ABSC01000183.1|provirus_1_11483_1,1,183,183,-1,0.464,11,AGGAG/GGAGG,GENOMAD.023403.VV,2.105000e-32,...,None,None,PF05263;TIGR01637,"phage transcriptional regulator, ArpU family",GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483,ABSC01000183.1,chromosome
2804900,ABSC01000183.1|provirus_1_11483_2,259,555,297,-1,0.397,11,AGGAG,GENOMAD.096602.VV,1.238000e-55,...,None,None,PF09953;COG4873,"Uncharacterized protein YkvS, DUF2187 family",GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483,ABSC01000183.1,chromosome
2804901,ABSC01000183.1|provirus_1_11483_3,579,884,306,-1,0.363,11,AGGAG,None,NaN,...,None,None,None,None,GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483,ABSC01000183.1,chromosome
2804902,ABSC01000183.1|provirus_1_11483_4,900,1097,198,-1,0.303,11,AGGAG,GENOMAD.093693.VV,3.811000e-21,...,None,None,None,None,GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483,ABSC01000183.1,chromosome
2804903,ABSC01000183.1|provirus_1_11483_5,1094,1393,300,-1,0.387,11,GGAG/GAGG,GENOMAD.183400.VP,8.799000e-13,...,None,None,None,None,GCA_000172875.1,virus,False,ABSC01000183.1|provirus_1_11483,ABSC01000183.1,chromosome

In [30]:
tem_provirus_em_plasmidio = (
    (provirus_genes["host_contig_type"] == "plasmid")
    .groupby(provirus_genes["sample_id"]).any()
    .reindex(metadata.index, fill_value=False).astype(int)
    .rename("tem_provirus_em_plasmidio")
)

tem_provirus_em_plasmidio.head()

sample
GCA_000216055.2    0
GCA_000316425.1    0
GCA_000223095.2    0
GCA_036761135.1    0
GCA_003670255.1    0
Name: tem_provirus_em_plasmidio, dtype: int64

In [31]:
tem_amr_provirus = (
    provirus_genes.groupby("sample_id")["has_amr"].any()
    .reindex(metadata.index, fill_value=False).astype(int)
    .rename("tem_amr_em_provirus")
)

tem_amr_provirus.head()

sample
GCA_000216055.2    0
GCA_000316425.1    0
GCA_000223095.2    0
GCA_036761135.1    0
GCA_003670255.1    0
Name: tem_amr_em_provirus, dtype: int64

In [32]:
print(tem_amr_provirus.sum(), "genomas com AMR em provírus")
print(tem_provirus_em_plasmidio.sum(), "genomas com provírus em plasmídeo")

26 genomas com AMR em provírus
129 genomas com provírus em plasmídeo

In [33]:
n_proviruses = (
    provirus_genes.groupby("sample_id")["seq_name"].nunique()
    .reindex(metadata.index, fill_value=0)
    .rename("n_proviruses")
)

n_proviruses.head()

sample
GCA_000216055.2    4
GCA_000316425.1    7
GCA_000223095.2    3
GCA_036761135.1    1
GCA_003670255.1    4
Name: n_proviruses, dtype: int64

## Fazendo a tabela final

In [47]:
raw_features = pd.concat([
    # resistoma — cromossomal vs plasmidial
    n_genes_cromossomal,
    n_genes_plasmidial,
    mdr_score_cromossomal,
    mdr_score_plasmidial,
    matriz_drugclass_plasmidial,          # n_plasmidial_<classe_de_droga>

    # estrutura de contig
    pct_contigs_cromossomal,
    pct_contigs_plasmidial,
    topology_pct,                          # pct_plasmid_topology_{dtr,itr,no_terminal_repeats}

    # mobilidade / conjugação
    pct_plasmidial_amr,
    pct_plasmidial_conjugacao_amr,
    n_genes_plasmidial_conjugativo,

    # virulência (VFDB)
    vfdb_plasmidial,                       
    virulence_score_plasmidial,
    virulence_score_cromossomal,

    # provírus
    n_proviruses,
    tem_provirus_em_plasmidio,
    tem_amr_provirus,
], axis=1)

print(raw_features.shape)
raw_features.head()

(7038, 50)

,n_genes_cromossomal,n_genes_plasmidial,mdr_score_cromossomal,mdr_score_plasmidial,n_plasmidial_aminoglycoside,n_plasmidial_antimycobacterial,n_plasmidial_beta-lactam,n_plasmidial_biocide_antiseptic,n_plasmidial_fluoroquinolone,n_plasmidial_glycopeptide,...,vfdb_plasmid_motility,vfdb_plasmid_nutritional_metabolic_factor,vfdb_plasmid_others,vfdb_plasmid_regulation,vfdb_plasmid_stress_survival,virulence_score_plasmidial,virulence_score_cromossomal,n_proviruses,tem_provirus_em_plasmidio,tem_amr_em_provirus
sample,,,,,,,,,,,,,,,,,,,,,
GCA_000216055.2,2,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,4,0,0
GCA_000316425.1,47,1,13,6,0,0,1,1,1,0,...,0,0,0,0,0,4,8,7,0,0
GCA_000223095.2,6,0,7,0,0,0,0,0,0,0,...,0,0,0,0,0,1,6,3,0,0
GCA_036761135.1,10,6,10,5,0,0,1,1,0,0,...,0,0,0,0,0,0,4,1,0,0
GCA_003670255.1,7,7,8,5,1,0,3,1,0,0,...,0,0,0,0,0,0,4,4,0,0

In [48]:
raw_features.to_csv('../data/raw/raw_features.csv')

## Exportando a lista de contigs cromossomais e plasmidiais de cada genoma pra calcular %GC

In [49]:
contigs_por_tipo = (
    dataset.contigs
    .groupby(["sample_id", "contig_type"])["seq_name"]
    .apply(list)
    .unstack("contig_type")
    .reindex(metadata.index)
)

contigs_cromossomais = contigs_por_tipo["chromosome"].apply(lambda x: x if isinstance(x, list) else [])
contigs_plasmidiais = contigs_por_tipo["plasmid"].apply(lambda x: x if isinstance(x, list) else [])

contig_lists = pd.DataFrame({
    "contigs_cromossomais": contigs_cromossomais,
    "contigs_plasmidiais": contigs_plasmidiais,
})
contig_lists.head()

,contigs_cromossomais,contigs_plasmidiais
sample,,
GCA_000216055.2,"[AFMI01000302.1, AFMI01000301.1, AFMI01000300....","[AFMI01000289.1, AFMI01000277.1, AFMI01000211...."
GCA_000316425.1,"[KB005709.1, KB005711.1, KB005715.1, KB005716....","[KB005710.1, KB005712.1, KB005713.1, KB005714...."
GCA_000223095.2,"[AFSV01000063.1, AFSV01000062.1, AFSV01000061....","[AFSV01000054.1, AFSV01000048.1, AFSV01000040...."
GCA_036761135.1,"[JBAISN010000001.1, JBAISN010000010.1, JBAISN0...","[JBAISN010000103.1, JBAISN010000104.1, JBAISN0..."
GCA_003670255.1,"[QWFV01000010.1, QWFV01000100.1, QWFV01000101....","[QWFV01000001.1, QWFV01000102.1, QWFV01000105...."

In [50]:
contig_lists.to_csv("../data/raw/contig_lists.csv")

## Adicionando %GC e salvando

In [51]:
gc = pd.read_csv("../data/raw/gc_stats.txt", sep=r"\s+")

gc.head()

,file,format,type,num_seqs,sum_len,min_len,avg_len,max_len,Q1,Q2,Q3,sum_gap,N50,N50_num,Q20(%),Q30(%),AvgQual,GC(%),sum_n
0,genomes_contig_type/GCA_000172875.1_ASM17287v1...,FASTA,DNA,293,"2,486,720",216,"8,487.1","150,593",996,"2,832","9,453",0,"22,620",28,0,0,0,37.94,0
1,genomes_contig_type/GCA_000172875.1_ASM17287v1...,FASTA,DNA,34,"364,754","2,531","10,728.1","36,405","4,772","9,614.5","12,656",0,"12,656",9,0,0,0,36.24,0
2,genomes_contig_type/GCA_000188755.2_ASM18875v2...,FASTA,DNA,116,"4,411,386",277,"38,029.2","222,066","2,212.5","19,067.5","51,921",0,"91,542",17,0,0,0,50.74,4
3,genomes_contig_type/GCA_000188755.2_ASM18875v2...,FASTA,DNA,36,"744,317",954,"20,675.5","90,331","7,710","13,332.5","26,628.5",0,"29,539",7,0,0,0,49.15,1
4,genomes_contig_type/GCA_000188815.2_ASM18881v2...,FASTA,DNA,46,"4,960,945",234,"107,846.6","730,778",683,"41,411.5","198,155",0,"249,753",7,0,0,0,50.84,0

In [52]:
gc["sample_id"] = gc["file"].str.extract(r"(GC[AF]_\d+\.\d+)")
gc["contig_type"] = gc["file"].str.extract(r"_(chromosome|plasmid)\.fna$")

gc.head()

,file,format,type,num_seqs,sum_len,min_len,avg_len,max_len,Q1,Q2,...,sum_gap,N50,N50_num,Q20(%),Q30(%),AvgQual,GC(%),sum_n,sample_id,contig_type
0,genomes_contig_type/GCA_000172875.1_ASM17287v1...,FASTA,DNA,293,"2,486,720",216,"8,487.1","150,593",996,"2,832",...,0,"22,620",28,0,0,0,37.94,0,GCA_000172875.1,chromosome
1,genomes_contig_type/GCA_000172875.1_ASM17287v1...,FASTA,DNA,34,"364,754","2,531","10,728.1","36,405","4,772","9,614.5",...,0,"12,656",9,0,0,0,36.24,0,GCA_000172875.1,plasmid
2,genomes_contig_type/GCA_000188755.2_ASM18875v2...,FASTA,DNA,116,"4,411,386",277,"38,029.2","222,066","2,212.5","19,067.5",...,0,"91,542",17,0,0,0,50.74,4,GCA_000188755.2,chromosome
3,genomes_contig_type/GCA_000188755.2_ASM18875v2...,FASTA,DNA,36,"744,317",954,"20,675.5","90,331","7,710","13,332.5",...,0,"29,539",7,0,0,0,49.15,1,GCA_000188755.2,plasmid
4,genomes_contig_type/GCA_000188815.2_ASM18881v2...,FASTA,DNA,46,"4,960,945",234,"107,846.6","730,778",683,"41,411.5",...,0,"249,753",7,0,0,0,50.84,0,GCA_000188815.2,chromosome

In [53]:
gc_wide = gc.pivot(index="sample_id", columns="contig_type", values="GC(%)")

gc_wide.head()

contig_type      chromosome  plasmid
sample_id
GCA_000172875.1       37.94    36.24
GCA_000188755.2       50.74    49.15
GCA_000188815.2       50.84    50.44
GCA_000188875.2       50.84    48.90
GCA_000208825.1       61.70    49.72

In [54]:
gc_wide.columns = ["gc_cromossomal", "gc_plasmidial"]
gc_wide["gc_diff_plasmid_cromossomo"] = gc_wide["gc_plasmidial"] - gc_wide["gc_cromossomal"]

gc_wide.head()

                 gc_cromossomal  gc_plasmidial  gc_diff_plasmid_cromossomo
sample_id
GCA_000172875.1           37.94          36.24                       -1.70
GCA_000188755.2           50.74          49.15                       -1.59
GCA_000188815.2           50.84          50.44                       -0.40
GCA_000188875.2           50.84          48.90                       -1.94
GCA_000208825.1           61.70          49.72                      -11.98

In [55]:
raw_features = pd.read_csv("../data/raw/raw_features.csv", index_col=0)

raw_features = raw_features.join(gc_wide, how="left")

print(raw_features.shape)

(7038, 53)

In [56]:
raw_features.head()

,n_genes_cromossomal,n_genes_plasmidial,mdr_score_cromossomal,mdr_score_plasmidial,n_plasmidial_aminoglycoside,n_plasmidial_antimycobacterial,n_plasmidial_beta-lactam,n_plasmidial_biocide_antiseptic,n_plasmidial_fluoroquinolone,n_plasmidial_glycopeptide,...,vfdb_plasmid_regulation,vfdb_plasmid_stress_survival,virulence_score_plasmidial,virulence_score_cromossomal,n_proviruses,tem_provirus_em_plasmidio,tem_amr_em_provirus,gc_cromossomal,gc_plasmidial,gc_diff_plasmid_cromossomo
sample,,,,,,,,,,,,,,,,,,,,,
GCA_000216055.2,2,0,1,0,0,0,0,0,0,0,...,0,0,0,0,4,0,0,34.95,35.13,0.18
GCA_000316425.1,47,1,13,6,0,0,1,1,1,0,...,0,0,4,8,7,0,0,50.57,47.65,-2.92
GCA_000223095.2,6,0,7,0,0,0,0,0,0,0,...,0,0,1,6,3,0,0,47.69,44.64,-3.05
GCA_036761135.1,10,6,10,5,0,0,1,1,0,0,...,0,0,0,4,1,0,0,37.79,38.10,0.31
GCA_003670255.1,7,7,8,5,1,0,3,1,0,0,...,0,0,0,4,4,0,0,37.95,38.85,0.90

In [57]:
sem_plasmidio = raw_features["pct_contigs_plasmidial"] == 0  

raw_features.loc[sem_plasmidio, "gc_plasmidial"] = np.nan
raw_features.loc[sem_plasmidio, "gc_diff_plasmid_cromossomo"] = np.nan

In [58]:
raw_features.head()

,n_genes_cromossomal,n_genes_plasmidial,mdr_score_cromossomal,mdr_score_plasmidial,n_plasmidial_aminoglycoside,n_plasmidial_antimycobacterial,n_plasmidial_beta-lactam,n_plasmidial_biocide_antiseptic,n_plasmidial_fluoroquinolone,n_plasmidial_glycopeptide,...,vfdb_plasmid_regulation,vfdb_plasmid_stress_survival,virulence_score_plasmidial,virulence_score_cromossomal,n_proviruses,tem_provirus_em_plasmidio,tem_amr_em_provirus,gc_cromossomal,gc_plasmidial,gc_diff_plasmid_cromossomo
sample,,,,,,,,,,,,,,,,,,,,,
GCA_000216055.2,2,0,1,0,0,0,0,0,0,0,...,0,0,0,0,4,0,0,34.95,35.13,0.18
GCA_000316425.1,47,1,13,6,0,0,1,1,1,0,...,0,0,4,8,7,0,0,50.57,47.65,-2.92
GCA_000223095.2,6,0,7,0,0,0,0,0,0,0,...,0,0,1,6,3,0,0,47.69,44.64,-3.05
GCA_036761135.1,10,6,10,5,0,0,1,1,0,0,...,0,0,0,4,1,0,0,37.79,38.10,0.31
GCA_003670255.1,7,7,8,5,1,0,3,1,0,0,...,0,0,0,4,4,0,0,37.95,38.85,0.90

In [59]:
raw_features.to_csv('../data/raw/raw_features_com_gc.csv')